data_dir: '/data/37day_final'

face:
    beta: 0.5
    topk: 32
    retrieval_t: 60
    agg_thre: 0.85
    nor_thre: 0.7
    ts_thre: 0.5
    sub_thre: 0.7
    max_sub_num: 10
    max_sub_index_num: 50
    max_sub_center_num: 100000
    min_sub_center_num: 50000
    max_density_while_merge: 1
    iteration: 2
    alpha: 0.2
    het_thre: 0.8
    pre_clustering_thre: 0.85

    bukong: False
    faiss_recall: True
    faiss_index_path: '/data/faiss_index/face_ivf8192flat.index'
    center_recall: True
    subcenter_ranking: True
    ts_filter: False
    cluster_merge: True
    time_retrieval: True
    het_sim_propogation: False


body:
    beta: 0.3
    topk: 64
    retrieval_t: 120
    agg_thre: 0.85
    nor_thre: 0.7
    ts_thre: 0.5
    sub_thre: 0.7
    max_sub_num: 15
    max_sub_index_num: 75
    max_sub_center_num: 100000
    min_sub_center_num: 50000
    max_density_while_merge: 10
    iteration: 2
    alpha: 0.2
    het_thre: 0.8
    pre_clustering_thre: 0.9

    bukong: False
    faiss_recall: True
    faiss_index_path: '/data/faiss_index/body_ivf8192flat.index'
    center_recall: True
    subcenter_ranking: True
    ts_filter: True
    cluster_merge: True
    time_retrieval: False
    het_sim_propogation: True
    ts_model: True

    ts_model_config:
        model_path: 'examples/real_time_clustering/params.model'
        max_len: 15
        embed_dim: 3
        nhid: 64
        num_head: 1
        dropout: 0.5
        layers: 2
        num_workers: 0
        device: "cpu"
        ts_model_thre: 0.85
